version: "3"

services:
  php:
    ports:
      - "3000:3000"



# version: '3'

# services:
# ###> doctrine/doctrine-bundle ###
#   database:
#     ports:
#       - "5432"
# ###< doctrine/doctrine-bundle ###



