version: "3"

services:
  php:
    container_name: php-container
    build: docker/php
    working_dir: /home/app
    volumes:
      - .:/home/app
      - ./docker/php/conf.d/app.ini:/usr/local/etc/php/conf.d/app.ini:ro
    networks:
      web:

  nginx:
    container_name: nginx-container
    image: nginx:stable-alpine
    volumes:
      - .:/home/app
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
    ports:
      - "80:80"
    networks:
      web:

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      web:
    
  minio:
    container_name: minio-container
    image: docker.io/bitnami/minio:2024
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
    ports:
      - "9001:9001"
    volumes:
      - 'storage:/data'
    networks:
      web:
        ipv4_address: 172.252.2.4

volumes:
  database_data:
  storage:

networks:
  web:
    ipam:
      config:
        - subnet: 172.252.2.0/24