version: "3"

services:
  php:
    container_name: php-container
    build: docker/php
    working_dir: /home/app
    volumes:
      - .:/home/app
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx-container
    image: nginx:stable-alpine
    volumes:
      - .:/home/app
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
    ports:
      - "80:80"

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
